### ISSUE TITLE
Problem compiling against iRODS 4.1.10

### ISSUE THREAD

**Issue by bnordgren** [EUDAT-B2STAGE/B2STAGE-GridFTP#16]
I had a working install on CentOS 7 and iRODS 4.1.9. Then I upgraded. I did a "make clean" in the build directory. Compiling against 4.1.10, when I attempt to start the gridftp server, I now get: 

    Nov 10 16:58:23 vault.usfs-i2.umt.edu globus-gridftp-server[29645]: Starting globus-gridftp-server: Server configuration error.
    Nov 10 16:58:23 vault.usfs-i2.umt.edu globus-gridftp-server[29645]: Couldn't load 'iRODS'. DSI activation failed.
    Nov 10 16:58:23 vault.usfs-i2.umt.edu globus-gridftp-server[29645]: globus_extension_module: Couldn't dlopen libglobus_gridftp_server_iRODS_gcc64.so in /usr/lib64 (or LD_LIBRARY_PATH): file not found
    Nov 10 16:58:23 vault.usfs-i2.umt.edu globus-gridftp-server[29645]: FAILED

My install directory is /opt/iRODS_DSI, and it contains: 

    [root@vault B2STAGE-GridFTP]# ls /opt/iRODS_DSI/
    gridmap_iRODS_callout.conf             libgridmap_iRODS_callout.so.1.8
    libglobus_gridftp_server_iRODS.so      testirodsmap
    libglobus_gridftp_server_iRODS.so.1.8  testpidmanager
    libgridmap_iRODS_callout.so

The `testirodsmap` executable is new, and it works. Will check next to see if I can build on a clean machine...

**Comment by bnordgren** [comment]
Just tried compiling again on a clean machine. Same result. I think it may be a problem with 4.1.10.

**Comment by muccix** [comment]
I have not tried to build against iRODS 4.1.10. I will test it in the next days.

**Comment by bnordgren** [comment]
It occurs to me that I updated to the current globus toolkit release between the builds as well (using the globus toolkit repository for CentOS 7.)  Not knowing exactly what might be important, here's the list of globus package versions I'm building against: 

    [root@lansing ~]# rpm -qa | grep globus
    globus-gsi-openssl-error-3.7-1.el7+gt6.x86_64
    globus-gsi-callback-5.12-1.el7+gt6.x86_64
    globus-callout-3.15-3.el7+gt6.x86_64
    globus-xio-5.14-1.el7+gt6.x86_64
    globus-ftp-control-7.7-2.el7+gt6.x86_64
    globus-authz-callout-error-3.6-3.el7+gt6.x86_64
    globus-usage-devel-4.5-3.el7+gt6.x86_64
    globus-openssl-module-devel-4.8-1.el7+gt6.x86_64
    globus-gsi-credential-devel-7.11-1.el7+gt6.x86_64
    globus-gssapi-error-devel-5.5-3.el7+gt6.x86_64
    globus-gridftp-server-control-devel-4.2-4.el7+gt6.x86_64
    globus-xio-udt-driver-1.25-1.el7+gt6.x86_64
    globus-gridmap-callout-error-devel-2.5-4.el7+gt6.x86_64
    globus-gsi-proxy-ssl-5.10-1.el7+gt6.x86_64
    globus-common-16.8-2.el7+gt6.x86_64
    globus-openssl-module-4.8-1.el7+gt6.x86_64
    globus-gsi-sysconfig-6.11-1.el7+gt6.x86_64
    globus-gsi-credential-7.11-1.el7+gt6.x86_64
    globus-gssapi-gsi-12.12-1.el7+gt6.x86_64
    globus-gss-assist-10.20-1.el7+gt6.x86_64
    globus-usage-4.5-3.el7+gt6.x86_64
    globus-proxy-utils-6.18-1.el7+gt6.x86_64
    globus-gssapi-error-5.5-3.el7+gt6.x86_64
    globus-io-11.8-1.el7+gt6.x86_64
    globus-gfork-4.9-4.el7+gt6.x86_64
    globus-gridftp-server-control-4.2-4.el7+gt6.x86_64
    globus-authz-3.15-1.el7+gt6.x86_64
    globus-common-devel-16.8-2.el7+gt6.x86_64
    globus-callout-devel-3.15-3.el7+gt6.x86_64
    globus-gfork-devel-4.9-4.el7+gt6.x86_64
    globus-authz-callout-error-devel-3.6-3.el7+gt6.x86_64
    globus-gsi-proxy-ssl-devel-5.10-1.el7+gt6.x86_64
    globus-gsi-sysconfig-devel-6.11-1.el7+gt6.x86_64
    globus-gsi-callback-devel-5.12-1.el7+gt6.x86_64
    globus-gsi-proxy-core-devel-8.6-1.el7+gt6.x86_64
    globus-gss-assist-devel-10.20-1.el7+gt6.x86_64
    globus-xio-gsi-driver-devel-3.10-3.el7+gt6.x86_64
    globus-ftp-control-devel-7.7-2.el7+gt6.x86_64
    globus-authz-devel-3.15-1.el7+gt6.x86_64
    globus-gridftp-server-11.8-1.el7+gt6.x86_64
    globus-gridftp-server-progs-11.8-1.el7+gt6.x86_64
    globus-toolkit-repo-6-23.noarch
    globus-gsi-cert-utils-9.15-1.el7+gt6.x86_64
    globus-gsi-proxy-core-8.6-1.el7+gt6.x86_64
    globus-xio-gsi-driver-3.10-3.el7+gt6.x86_64
    globus-xio-pipe-driver-3.9-3.el7+gt6.x86_64
    globus-gridmap-callout-error-2.5-4.el7+gt6.x86_64
    globus-xio-devel-5.14-1.el7+gt6.x86_64
    globus-xio-pipe-driver-devel-3.9-3.el7+gt6.x86_64
    globus-gsi-openssl-error-devel-3.7-1.el7+gt6.x86_64
    globus-gsi-cert-utils-devel-9.15-1.el7+gt6.x86_64
    globus-gssapi-gsi-devel-12.12-1.el7+gt6.x86_64
    globus-io-devel-11.8-1.el7+gt6.x86_64
    globus-gridftp-server-devel-11.8-1.el7+gt6.x86_64

**Comment by bnordgren** [comment]
Tinkering with it today, the problem seems to be that LD_LIBRARY_PATH is just not getting set (or getting set in time) when I use the gridftp.conf file to set it. Setting LD_LIBRARY_PATH in the globus-gridftp-server file instead seems to fix the problem on both my upgraded server and my clean server. My pull request #17 reflects this change in the README.  Since this was working on my previous setup, I assume something has recently changed within the gridftp server.

**Comment by muccix** [comment]
Thanks @bnordgren
