### ISSUE TITLE
bug: user_name pointer is being used after it is freed

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [EUDAT-B2STAGE/B2STAGE-GridFTP#2]
Hi,

Unfortunately, 7e60ec16c8b7f8b5fbf850e62fd190ffcdb495f4 re-introduces a bug fixed in #1: using the user_name pointer after it has been freed.  That means at that point, the value it points to could have been corrupted by anything else happening in the system, or just overwritten by the memory manager for keeping track of free space (this behavior depends on the particular malloc implementation).

I am trying to understand the justification given in #1 for why to free the user_name pointer before setting home_dir.

Is it that to set the home directory to be set to just ````"/<zone>/home"```` ?

This would be best achieved by passing an empty string for the last parameter to the globus_common_create_string function.  And this would be best done through a configuration entry.

But freeing the pointer and then using it again can lead to unpredictable results.  If lucky, the first byte of the string the pointer points to gets set to '\0', causing it to appear as empty string.  On my system, I am just getting plain garbage out of it - prior to also fixing the zone name, I was getting home_dir set to: ````"/(null)/home//(nu"````.

I might have a go at implementing this as a configuration item - would you think tweaking this via environment variables (passed from gridftp.conf) would be a good idea?

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Hi Roberto,

Thanks for the reply.  I've just come back from holidays and I'm now picking things up from where I left them.

The intention of the current code - line 588, https://github.com/EUDAT-B2STAGE/B2STAGE-GridFTP/blob/master/globus_gridftp_server_iRODS.c#L588:

````
finished_info.info.session.home_dir = globus_common_create_string("/%s/home/%s", iRODS_handle->zone, user_name);
````

appears to be to do ````"/<zone>/home/<username>"```` - and it was more just the interaction of this bug (using pointer after it is freed) and the particular malloc implementation interpreting such a pointer as empty string that resulted into defaulting to ````"/<zone>/home"```` on your system.

Also, the convention on most systems is to set the home directory to the actual home directory of the current user, not just the parent container directory.

I understand this scheme does not work for you, and I know if the default (together with the bugfix) changes the behaviour, you'd have to change the configuration file on your deployment .... but to me, that seem to be the right thing to do.

Would you be fine with that?

Cheers,
Vlad

**Comment by muccix** [comment]
Hi Vlad,

I agree with you: let's set as default the full path, including the username.

Thanks again

Cheers,
Roberto
