### ISSUE TITLE
globus_url_copy hangs when attempting a transfer in Centos 6.7

### ISSUE THREAD

**Issue by JustinKyleJames** [EUDAT-B2STAGE/B2STAGE-GridFTP#22]
I'm using iRODS 4.1.10 on Centos and after installing the Globus tools and the iRODS plugin and attempting to transfer a file from a client on a different machine to the server, the client hangs.

Here's the command I ran on the client:

`globus-url-copy file.dat gsiftp://server.example.org:2811/tempZone/home/rods/`

I can provide the scripts I used to install and configure everything if that helps:

Notes:

1.  I first encountered this when testing against 4.2.  I went back to the original 4.1 code to make sure the problem wasn't dependent on my changes.

2.  I have the firewall and SELinux disabled on both the client and server.

3.  If the client is collocated with the server (same machine) I do not have this problem.

4.  This works fine on two Ubuntu machines.  An Ubuntu client communicating with a Centos server will also hang.

**Comment by muccix** [comment]
Could you try using the -ipv6 option of globus-url-copy? I had a similar problem risolved that way

**Comment by muccix** [comment]
I'm closing this. Feel free to reopen if you still have the issue
