### ISSUE TITLE
Provide partial directory listings

### ISSUE THREAD

**Issue by JustinKyleJames** [EUDAT-B2STAGE/B2STAGE-GridFTP#23]
We have had a request for the GridFTP plugin to provide the ability for partial directory listings.  This issue is to track that request and to provide more information as necessary.

**Comment by muccix** [comment]
What do you mean by "partial directory listings"? Something like "list only a certain number of elements instead of all"?
Is there andy GridFTP client supporting this?

**Comment by JustinKyleJames** [comment]
We worked with Globus and this was done in our fork under the irods namespace.  I am closing this.
