### ISSUE TITLE
Request realpath feature

### ISSUE THREAD

**Issue by JustinKyleJames** [EUDAT-B2STAGE/B2STAGE-GridFTP#24]
I see that it is possible to address files by both a path namespace as well as an object id, so depending on how that works it may also make sense to implement the realpath feature, which would enable path restrictions to work.

**Comment by muccix** [comment]
Is the "realpath" the physical location of an iRODS object (the path on the backend filesystem)?

**Comment by trel** [comment]
Yes, that is correct - the physical path on the storage filesystem.   Thanks.

**Comment by JustinKyleJames** [comment]
This was implemented with the help of Globus in the irods fork.  Closing this issue.
